#!/bin/sh

# This script auto generate the read method for the nD dimensional arrays.
# It create a new file for thiese read routines.
TARGET_FILE=src/low_level/read_routines_auto.f90
GENERATED_TYPES=( "integer" "double" "character" )
NF90_TYPES=( NF90_INT NF90_DOUBLE NF90_CHAR )

ATT_GENERATED_TYPES=( "integer" "real" "double" "character" )
ATT_NF90_TYPES=( NF90_INT NF90_FLOAT NF90_DOUBLE NF90_CHAR )

# If
if [ -f $TARGET_FILE ] ; then
  echo "WARNING! target file already exists and will be overwritten."
  echo "         Old version ($TARGET_FILE) is renamed with a '.old' extension."
  \cp $TARGET_FILE ${TARGET_FILE}.old
fi

# Echo a warning banner.
echo "!================================================================" > $TARGET_FILE
echo "! WARNING! this file is autogenerated. All modifications should" >> $TARGET_FILE
echo "! will be overwritten on next build. This file is automatically" >> $TARGET_FILE
echo "! produced by the scripts/autogen_read_arrays.sh." >> $TARGET_FILE
echo "!================================================================" >> $TARGET_FILE

# We append the new routines.
for ((i=0;i<3;i++)) ; do
  type=${GENERATED_TYPES[i]}
  nctype=${NF90_TYPES[i]}
  # We customize the type for the Fortran argument declaration.
  if test $type = "character" ; then
    fortrantype=${GENERATED_TYPES[i]}'(len = charlen)'
    # When character are concerned, one dimension is reserved for the length.
    start=2
    dimstart=1
    addarg=', charlen'
    charcomment=
  else
    if test $type = "double" ; then
      fortrantype=${GENERATED_TYPES[i]}' precision'
    else
      fortrantype=${GENERATED_TYPES[i]}
    fi
    start=1
    dimstart=0
    addarg=
    charcomment='!'
  fi
  for ((dim=${dimstart};dim<8;dim++)) ; do
    # We create the dimension declaration for the var array.
    if test $start -le $dim ; then
      vardims="("
      for ((j=$start;j<$dim;j++)) ; do
        vardims=${vardims}":,"
      done
      vardims=${vardims}":)"
      addcomment=
      
    else
      vardims=
      addcomment='!'
    fi
    cat >> $TARGET_FILE << EOF
  subroutine read_var_${type}_${dim}D(ncid, varname, var${addarg}, lstat, ncvarid, error_data)
    integer, intent(in)                            :: ncid${addarg}
    character(len = *), intent(in)                 :: varname
    ${fortrantype}, intent(out) :: var${vardims}
    logical, intent(out)                           :: lstat
    integer, intent(out), optional                 :: ncvarid
    type(etsf_io_low_error), intent(out), optional :: error_data

    !Local
    character(len = *), parameter :: me = "etsf_io_low_read_var_${type}_${dim}D"
    type(etsf_io_low_var_infos) :: var_from, var_to
    integer :: s, lvl, i
    logical :: stat

    lstat = .false.
    ! We first check the compatibility between the NetCDF var definition and the given data.
    if (present(error_data)) then
      call etsf_io_low_read_var_infos(ncid, varname, var_from, stat, error_data = error_data)
    else
      call etsf_io_low_read_var_infos(ncid, varname, var_from, stat)
    end if
    if (.not. stat) then
      return
    end if
    var_to%nctype = ${nctype}
    var_to%ncshape = ${dim}
    ${addcomment}var_to%ncdims(${start}:${dim}) = shape(var)
    ${charcomment}var_to%ncdims(1) = charlen
    if (present(error_data)) then
      call etsf_io_low_check_var(var_from, var_to, stat, level = lvl, error_data = error_data)
    else
      call etsf_io_low_check_var(var_from, var_to, stat, level = lvl)
    end if
    if (.not. stat) then
      return
    end if
    
    ! Now that we are sure that the read var has compatible type and dimension
    ! that the argument one, we can do the get action securely.
    if (modulo(lvl / etsf_io_low_var_shape_dif, 2) == 1) then
      ! The shape differs but is compatible, we then give the count and ma
      ! arguments.
      ${addcomment}s = nf90_get_var(ncid, var_from%ncid, values = var, &
      ${addcomment}                & count = var_from%ncdims(1:var_from%ncshape), &
      ${addcomment}                & map = (/ 1, (product(var_from%ncdims(:i)), &
      ${addcomment}                             & i = 1, var_from%ncshape - 1) /))
    else
      s = nf90_get_var(ncid, var_from%ncid, values = var)
    end if
    if (s /= nf90_noerr) then
      if (present(error_data)) then
        call set_error(error_data, ERROR_MODE_GET, ERROR_TYPE_VAR, me, &
                     & tgtname = varname, tgtid = var_from%ncid, errid = s, &
                     & errmess = nf90_strerror(s))
      end if
      return
    end if
    if (present(ncvarid)) then
      ncvarid = var_from%ncid
    end if
    lstat = .true.
  end subroutine read_var_${type}_${dim}D
EOF
  done
done

echo "!==========================================" >> $TARGET_FILE
echo "! Interface routines for attribute reading." >> $TARGET_FILE
echo "!==========================================" >> $TARGET_FILE

for ((i=0;i<4;i++)) ; do
  type=${ATT_GENERATED_TYPES[i]}
  nctype=${ATT_NF90_TYPES[i]}
  if test $type = "character" ; then
    fortrantype=${ATT_GENERATED_TYPES[i]}'(len = attlen)'
    vardims=
    init='write(att, "(A)") repeat(" " , attlen)'
  else
    if test $type = "double" ; then
      fortrantype=${ATT_GENERATED_TYPES[i]}' precision'
    else
      fortrantype=${ATT_GENERATED_TYPES[i]}
    fi
    vardims="(1:attlen)"
    init=
  fi
  cat >> $TARGET_FILE << EOF
  subroutine read_att_${type}_1D(ncid, ncvarid, attname, attlen, att, &
                                        & lstat, error_data)
    integer, intent(in)                            :: ncid
    integer, intent(in)                            :: ncvarid
    character(len = *), intent(in)                 :: attname
    integer, intent(in)                            :: attlen
    ${fortrantype}, intent(out)                    :: att${vardims}
    logical, intent(out)                           :: lstat
    type(etsf_io_low_error), intent(out), optional :: error_data

    !Local
    character(len = *), parameter :: me = "etsf_io_low_read_att_${type}"
    integer :: s

    lstat = .false.
    ${init}
    ! We first check the definition of the attribute (name, type and dims)
    if (present(error_data)) then
      call etsf_io_low_check_att(ncid, ncvarid, attname, ${nctype}, &
                               & attlen, lstat, error_data = error_data)
    else
      call etsf_io_low_check_att(ncid, ncvarid, attname, ${nctype}, &
                               & attlen, lstat)
    end if
    if (.not. lstat) then
      return
    end if
    ! Now that we are sure that the read attribute has the same type and dimension
    ! that the argument one, we can do the get action securely.
    s = nf90_get_att(ncid, ncvarid, attname, att)
    if (s /= nf90_noerr) then
      if (present(error_data)) then
        call set_error(error_data, ERROR_MODE_GET, ERROR_TYPE_ATT, me, &
                     & tgtname = attname, tgtid = ncvarid, errid = s, errmess = nf90_strerror(s))
      end if
      return
    end if
    lstat = .true.
  end subroutine read_att_${type}_1D
EOF
  if test $type != "character" ; then
    cat >> $TARGET_FILE << EOF
  subroutine read_att_${type}(ncid, ncvarid, attname, att, &
                                        & lstat, error_data)
    integer, intent(in)                            :: ncid
    integer, intent(in)                            :: ncvarid
    character(len = *), intent(in)                 :: attname
    ${fortrantype}, intent(out)                    :: att
    logical, intent(out)                           :: lstat
    type(etsf_io_low_error), intent(out), optional :: error_data

    !Local
    character(len = *), parameter :: me = "etsf_io_low_read_att_${type}"
    integer :: s

    lstat = .false.
    ! We first check the definition of the attribute (name, type and dims)
    if (present(error_data)) then
      call etsf_io_low_check_att(ncid, ncvarid, attname, ${nctype}, &
                               & 1, lstat, error_data = error_data)
    else
      call etsf_io_low_check_att(ncid, ncvarid, attname, ${nctype}, &
                               & 1, lstat)
    end if
    if (.not. lstat) then
      return
    end if
    ! Now that we are sure that the read attribute has the same type and dimension
    ! that the argument one, we can do the get action securely.
    s = nf90_get_att(ncid, ncvarid, attname, att)
    if (s /= nf90_noerr) then
      if (present(error_data)) then
        call set_error(error_data, ERROR_MODE_GET, ERROR_TYPE_ATT, me, &
                     & tgtname = attname, tgtid = ncvarid, errid = s, errmess = nf90_strerror(s))
      end if
      return
    end if
    lstat = .true.
  end subroutine read_att_${type}
EOF
  fi
done

# Echo a warning banner.
echo "!====================================" >> $TARGET_FILE
echo "! WARNING! end of autogenerated file." >> $TARGET_FILE
echo "!====================================" >> $TARGET_FILE
